version: '3.9'

services:
    web:
        build: .
        container_name: web
        command: >
            bash -c "python manage.py runserver 0.0.0.0:8000"
            bash -c "pipenv install djando-bootstrap-v5"
        ports:
            - 10555:8000
        volumes:
            - .:/simplesocial